In [1]:
import pandas as pd

# Comparing two Pandas series
series1 = pd.Series([4, 65, 436, 3, 9])
series2 = pd.Series([7, 0, 3, 897, 9])
comparison = series1 == series2
print("Comparison of elements in series1 and series2:")
print(comparison)

Comparison of elements in series1 and series2:
0    False
1    False
2    False
3    False
4     True
dtype: bool

In [2]:
# Performing arithmetic operations on two Pandas series
series3 = pd.Series([2, 4, 6, 8, 14])
series4 = pd.Series([1, 3, 5, 7, 9])
addition = series3 + series4
subtraction = series3 - series4
multiplication = series3 * series4
division = series3 / series4
print("\nAddition of series3 and series4:")
print(addition)
print("\nSubtraction of series3 and series4:")
print(subtraction)
print("\nMultiplication of series3 and series4:")
print(multiplication)
print("\nDivision of series3 and series4:")
print(division)

Addition of series3 and series4:
0     3
1     7
2    11
3    15
4    23
dtype: int64

Subtraction of series3 and series4:
0    1
1    1
2    1
3    1
4    5
dtype: int64

Multiplication of series3 and series4:
0      2
1     12
2     30
3     56
4    126
dtype: int64

Division of series3 and series4:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.555556
dtype: float64

In [3]:
# Converting a dictionary to a Pandas series
dictionary1 = {'Josh': 24, 'Sam': 36, 'Peace': 19, 'Charles': 65, 'Tom': 44}
series5 = pd.Series(dictionary1)
print("\nDictionary converted to a Pandas series:")
print(series5)

# Converting a given series to an array
series6 = pd.Series(['Love', 800, 'Joy', 789.9, 'Peace', True])
array6 = series6.to_numpy()
print("\nSeries converted to an array:")
print(array6)

Dictionary converted to a Pandas series:
Josh       24
Sam        36
Peace      19
Charles    65
Tom        44
dtype: int64

Series converted to an array:
['Love' 800 'Joy' 789.9 'Peace' True]

In [4]:
# Displaying the most frequent value in the given series and replacing everything else as 'Other'
series7 = pd.Series(['Goal', 'Goal', 'Goal', 'Own Goal', 'Goal', 'Own Goal'])
most_frequent_value = series7.mode()[0]
series7 = series7.apply(lambda x: x if x == most_frequent_value else 'Other')
print("\nSeries with most frequent value and 'Other':")
print(series7)

Series with most frequent value and 'Other':
0     Goal
1     Goal
2     Goal
3    Other
4     Goal
5    Other
dtype: object